### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by devjoseadolfo**

### CODE REVIEW

**Review by thisIsTheFoxe — APPROVED** [review]
lgtm, I assume your GitHub repo is still private and the URL is correct?

**Comment by devjoseadolfo** [comment]
Yes, it will be up once the contest deadline is over.

**Comment by thisIsTheFoxe** [comment]
No worries.. We'll start merging soon and set up the website :)

**Comment by thisIsTheFoxe** [comment]
sorry, just saw #4 nvm

For the future, if you commit on the branch you made the pull request with it will automatically update the PR, so you don't need to make a new PR every time ;)

**Pull request closed without merging**
