### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by gokulnair2001**
Would suggest you to add a License on this repository, this would always help to safeguard this public repo. Such licenses are always preferable from Github too. Do have a look.

 Right now the license is pretty basic. You can make changes accordingly.

Or if you want I can make the changes, do let me know whatever the update is.

### CODE REVIEW

**Comment by zmknox** [comment]
I was thinking about this too, but I'm not really sure what the need would be for this repo in particular—which is just a big table of links. If we do add one, I think a permissive license like the MIT you provided would be preferred.

What I _don't_ want to happen is for someone to see whatever license we choose as "it's okay to scrape these students' GitHub accounts so we can spam them". Which maybe they're sadly doing anyway, but I wouldn't want to endorse it.

**Comment by gokulnair2001** [comment]
> I was thinking about this too, but I'm not really sure what the need would be for this repo in particular—which is just a big table of links. If we do add one, I think a permissive license like the MIT you provided would be preferred.
> 
> What I _don't_ want to happen is for someone to see whatever license we choose as "it's okay to scrape these students' GitHub accounts so we can spam them". Which maybe they're sadly doing anyway, but I wouldn't want to endorse it.

Got your point, but still I feel since its a collection of resource for upcoming SSC students we must add a license, and that to being an Open-source file I feel its kind of required. 

Do let me know what you think :)

**Comment by chih98** [comment]
I don't really know what's exactly licensable in this repro, but I do think adding some terms regarding the use, sharing, etc of the document have the possibility of becoming handy in the future

**Comment by gokulnair2001** [comment]
> I don't really know what's exactly licensable in this repro, but I do think adding some terms regarding the use, sharing, etc of the document have the possibility of becoming handy in the future

great ✌️

**Pull request closed without merging**
