### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by matheusvtna**
Probably something went wrong with my playground status, so I'm opening this pull request to update the information.

### CODE REVIEW

**Comment by thisIsTheFoxe** [comment]
I'm so sorry this happened and thanks you so much for noticing 👏 
We also had a similar issue recently (#189)

Original PR: #126 
Error introduced in: #124, probably due to re-merging older changes..?

**Review by thisIsTheFoxe — CHANGES_REQUESTED** [review]
Also, would you mind to move your entry up by one so it matches the alphabetical order? Thanks :)

**Comment by matheusvtna** [comment]
> Also, would you mind to move your entry up by one so it matches the alphabetical order? Thanks :)

Yes, I already fixed it. And, about the merge error, no problem. Thanks for helping me. Do I need to change anything else to accept the Pull Request?

**Review by thisIsTheFoxe — APPROVED** [review]
Thanks for fixing it so quickly, looks all good to me... 
And no worries I just wanna wait for @zmknox to check it out, so we can hopefully avoid those issues in the future ^-^

Btw, congrats again for winning.. 🥳

**Comment by matheusvtna** [comment]
> Thanks for fixing it so quickly, looks all good to me...
> And no worries I just wanna wait for @zmknox to check it out, so we can hopefully avoid those issues in the future ^-^
> 
> Btw, congrats again for winning..

Thank you so much for the help! XD

**Comment by thisIsTheFoxe** [comment]
Ahhhhh.. looks like Zach is not active rn.. 
I'll merge it for now. Thank you again for noticing and sorry you had to wait.. 😅

**Pull request merged**
